services:
  accounts:
    image: kksit/accounts:0.0.1
    container_name: accounts
    ports:
      - 8080:8080
    networks:
      - bank-network
    deploy:
      resources:
        limits:
          memory: 700m
  loans:
    image: kksit/loans:0.0.1
    container_name: loans
    ports:
      - 8090:8090
    networks:
      - bank-network
    deploy:
      resources:
        limits:
          memory: 700m
  cards:
    image: kksit/cards:0.0.1
    container_name: cards
    ports:
      - 9000:9000
    networks:
      - bank-network
    deploy:
      resources:
        limits:
          memory: 700m

networks:
  bank-network:
    driver: "bridge"